apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-discount
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      sr: web
  template:
    metadata:
      labels:
        sr: web
    spec:
      containers:
      - name: rest-discount
        image: pawan/rest-discount
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: rest-discount-entrypoint
  namespace: demo
spec:
  type: NodePort
  selector:
    sr: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001